#!/bin/bash 
#PBS -N jlh_2spins_split_20120605_184351 
#PBS -q batch 
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00 
#PBS -m bea -M jotelha@zedat.fu-berlin.de 
#PBS -e jlh_2spins_split_20120605_184351
#PBS -o jlh_2spins_split_20120605_184351
#PBS -W depend=afterok:40566.torque.physik.fu-berlin.de:40567.torque.physik.fu-berlin.de:40568.torque.physik.fu-berlin.de
cd $PBS_O_WORKDIR

/net/opt/bin/matlab -nodesktop -nosplash -r "jlh_sum_results('jlh_2spins_split_20120605_184351/jlh_2spins_split_20120605_184351.mat'); quit;" &> jlh_2spins_split_20120605_184351/jlh_2spins_split_20120605_184351.log
