% Second-rank Wigner rotation matrix as a function of Euler angles.
%
% Rows and columns of the matrix are sorted by descending rank, that is
%    
%                         [D( 2,2)  ...  D( 2,-2)
%                            ...    ...    ...  
%                          D(-2,2)  ...  D(-2,-2)]
%
% The resulting Wigner matrix is to be used as v=W*v, where v is a column
% vector of irreducible components, listed vertically in the following
% order: (2,2) (2,1) (2,0) (2,-1) (2,-2)
% 
% ilya.kuprov@oerc.ox.ac.uk

function wigner=euler2wigner(arg1,arg2,arg3)

% Adapt to the input style
if nargin==1
    alpha=arg1(1); beta=arg1(2); gamma=arg1(3);
elseif nargin==3
    alpha=arg1; beta=arg2; gamma=arg3;
else
    error('euler2wigner: incorrect number of input arguments.');
end

wigner=[...
    exp(-1i*2*gamma)*     cos(beta/2)^4*                     exp(-1i*2*alpha), ...
    exp(-1i*2*gamma)*     sin(beta)*(1+cos(beta))/2*         exp(-1i*1*alpha), ...
    exp(-1i*2*gamma)*     sqrt(3/8)*sin(beta)^2*             exp(-1i*0*alpha), ...
    exp(-1i*2*gamma)*     (-sin(beta)*(cos(beta)-1)/2)*      exp(-1i*(-1)*alpha), ...
    exp(-1i*2*gamma)*     sin(beta/2)^4*                     exp(-1i*(-2)*alpha); ...

    exp(-1i*1*gamma)*     (-sin(beta)*(1+cos(beta))/2)*      exp(-1i*2*alpha), ...
    exp(-1i*1*gamma)*     (2*cos(beta)-1)*(cos(beta)+1)/2*   exp(-1i*1*alpha), ...
    exp(-1i*1*gamma)*     sqrt(3/2)*sin(beta)*cos(beta)*     exp(-1i*0*alpha), ...
    exp(-1i*1*gamma)*     (2*cos(beta)+1)*(1-cos(beta))/2*   exp(-1i*(-1)*alpha), ...
    exp(-1i*1*gamma)*     (-sin(beta)*(cos(beta)-1)/2)*      exp(-1i*(-2)*alpha); ...

    exp(-1i*0*gamma)*     sqrt(3/8)*sin(beta)^2*             exp(-1i*2*alpha), ...
    exp(-1i*0*gamma)*     (-sqrt(3/2)*sin(beta)*cos(beta))*  exp(-1i*1*alpha), ...
    exp(-1i*0*gamma)*     (3*cos(beta)^2-1)/2*               exp(-1i*0*alpha), ...
    exp(-1i*0*gamma)*     sqrt(3/2)*sin(beta)*cos(beta)*     exp(-1i*(-1)*alpha), ...
    exp(-1i*0*gamma)*     sqrt(3/8)*sin(beta)^2*             exp(-1i*(-2)*alpha); ...

    exp(-1i*(-1)*gamma)*  sin(beta)*(cos(beta)-1)/2*         exp(-1i*2*alpha), ...
    exp(-1i*(-1)*gamma)*  (2*cos(beta)+1)*(1-cos(beta))/2*   exp(-1i*1*alpha), ...
    exp(-1i*(-1)*gamma)*  (-sqrt(3/2)*sin(beta)*cos(beta))*  exp(-1i*0*alpha), ...
    exp(-1i*(-1)*gamma)*  (2*cos(beta)-1)*(cos(beta)+1)/2*   exp(-1i*(-1)*alpha), ...
    exp(-1i*(-1)*gamma)*  sin(beta)*(1+cos(beta))/2*         exp(-1i*(-2)*alpha); ...

    exp(-1i*(-2)*gamma)*  sin(beta/2)^4*                     exp(-1i*2*alpha), ...
    exp(-1i*(-2)*gamma)*  sin(beta)*(cos(beta)-1)/2*         exp(-1i*1*alpha), ...
    exp(-1i*(-2)*gamma)*  sqrt(3/8)*sin(beta)^2*             exp(-1i*0*alpha), ...
    exp(-1i*(-2)*gamma)*  (-sin(beta)*(1+cos(beta))/2)*      exp(-1i*(-1)*alpha), ...
    exp(-1i*(-2)*gamma)*  cos(beta/2)^4*                     exp(-1i*(-2)*alpha)];
end

% ...there is nothing of any importance in life - except how well you do
% your work. Nothing. Only that. Whatever else you are, will come from
% that. It's the only measure of human value. All the codes of ethics
% they'll try to ram down your throat are just so much paper money put out
% by swindlers to fleece people of their virtues. The code of competence is
% the only system of morality that's on a gold standard. When you grow up,
% you'll know what I mean.
%
% Ayn Rand, "Atlas Shrugged"

